kind: Service
apiVersion: v1
metadata:
  name: auth-service
spec:
  type: NodePort
  selector:
    app: auth-deployment
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30004
---
kind: Service
apiVersion: v1
metadata:
  name: profile-service
spec:
  type: NodePort
  selector:
    app: profile-deployment
  ports:
  - protocol: TCP
    port: 3001
    targetPort: 3001
    nodePort: 30001
---
kind: Service
apiVersion: v1
metadata:
  name: apibroker-service
spec:
  type: NodePort
  selector:
    app: apibroker-deployment
  ports:
  - protocol: TCP
    port: 3002
    targetPort: 3002
    nodePort: 30006
---
kind: Service
apiVersion: v1
metadata:
  name: apigateway-service
spec:
  type: NodePort
  selector:
    app: apigateway-deployment
  ports:
  - protocol: TCP
    port: 3003
    targetPort: 3003
    nodePort: 30003
---
kind: Service
apiVersion: v1
metadata:
  name: recoengine-service
spec:
  type: NodePort
  selector:
    app: recoengine-deployment
  ports:
  - protocol: TCP
    port: 8001
    targetPort: 8001
    nodePort: 30005
---
kind: Service
apiVersion: v1
metadata:
  name: ui-service
spec:
  type: NodePort
  selector:
    app: ui-deployment
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30007
  externalIPs:
    - 149.165.156.244
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway-deployment
  labels:
    app: apigateway-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apigateway-deployment
  template:
    metadata:
      labels:
        app: apigateway-deployment
    spec:
      containers:
      - name: apigateway-deployment
        image: n0485/apigateway:latest
        ports:
        - containerPort: 3003
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-deployment
  labels:
    app: profile-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: profile-deployment
  template:
    metadata:
      labels:
        app: profile-deployment
    spec:
      containers:
      - name: profile-deployment
        image: n0485/profile:latest
        ports:
        - containerPort: 3001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  labels:
    app: auth-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-deployment
  template:
    metadata:
      labels:
        app: auth-deployment
    spec:
      containers:
      - name: auth-deployment
        image: n0485/auth:latest
        ports:
        - containerPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recoengine-deployment
  labels:
    app: recoengine-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: recoengine-deployment
  template:
    metadata:
      labels:
        app: recoengine-deployment
    spec:
      containers:
      - name: recoengine-deployment
        image: n0485/recoengine:latest
        ports:
        - containerPort: 8001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apibroker-deployment
  labels:
    app: apibroker-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apibroker-deployment
  template:
    metadata:
      labels:
        app: apibroker-deployment
    spec:
      containers:
      - name: apibroker-deployment
        image: n0485/apibroker:latest
        ports:
        - containerPort: 3002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-deployment
  labels:
    app: ui-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ui-deployment
  template:
    metadata:
      labels:
        app: ui-deployment
    spec:
      containers:
      - name: ui-deployment
        image: n0485/ui:latest
        ports:
        - containerPort: 3000
